---
- name: Run MongoDB Backup
  hosts: mongos
  become: yes
  vars:
    backup_script: /home/mongodb/scripts/Backup.sh
  tasks:
    - name: Execute Backup.sh
      shell: |
        bash {{ backup_script }}
      register: backup_output

    - name: Show backup output
      debug:
        var: backup_output.stdout_lines

