---
- name: Run MongoDB Backup
  hosts: g1
  become: yes
  vars:
    backup_script: /usr/local/bin/mongo_backup.sh
  tasks:
    - name: Execute Backup.sh
      shell: |
        bash {{ backup_script }}
      register: backup_output

    - name: Show backup output
      debug:
        var: backup_output.stdout_lines

