---
- name: Initiate config replica set with priorities
  hosts: n2  # Initiate from n2 (intended primary)
  become: yes
  vars:
    config_replset_name: configReplSet
    config_port: 27051
  tasks:
    - name: Initiate config replica set from n2 with dynamic IPs and priorities
      ansible.builtin.shell: |
        mongosh --host localhost --port {{ config_port }} <<'JS'
        rs.initiate({
          _id: "{{ config_replset_name }}",
          configsvr: true,
          members: [
            { _id: 0, host: "{{ hostvars['n2']['ansible_host'] }}:{{ config_port }}", priority: 2 },
            { _id: 1, host: "{{ hostvars['n3']['ansible_host'] }}:{{ config_port }}", priority: 1 },
            { _id: 2, host: "{{ hostvars['n1']['ansible_host'] }}:{{ config_port }}", priority: 0 }
          ]
        });
        JS
      args:
        executable: /bin/bash
      register: configReplSet_init

    - name: Show output of config replica set initiation
      debug:
        var: configReplSet_init.stdout
