---
- name: Setup and start mongos router
  hosts: n1
  become: yes
  vars:
    mongos_port: 27054
    log_path: /var/log/mongodb/mongos1.log

    # Shard and config ports
    config1_port: 27051
    config2_port: 27051
    config3_port: 27051
    shard1_port: 27052
    shard2_port: 27053

  tasks:
    - name: Set configReplSet connection string
      set_fact:
        config_replset: "configReplSet/{{ hostvars['n1']['ansible_host'] }}:{{ config1_port }},{{ hostvars['n2']['ansible_host'] }}:{{ config2_port }},{{ hostvars['n3']['ansible_host'] }}:{{ config3_port }}"

    - name: Set rsShard1 connection string
      set_fact:
        rsshard1: "rsShard1/{{ hostvars['n2']['ansible_host'] }}:{{ shard1_port }},{{ hostvars['n3']['ansible_host'] }}:{{ shard1_port }},{{ hostvars['n1']['ansible_host'] }}:{{ shard1_port }}"

    - name: Set rsShard2 connection string
      set_fact:
        rsshard2: "rsShard2/{{ hostvars['n3']['ansible_host'] }}:{{ shard2_port }},{{ hostvars['n2']['ansible_host'] }}:{{ shard2_port }},{{ hostvars['n1']['ansible_host'] }}:{{ shard2_port }}"

    - name: Ensure mongos log file exists
      file:
        path: "{{ log_path }}"
        state: touch
        owner: mongodb
        group: mongodb
        mode: '0644'

    - name: Start mongos router (forked, background)
      ansible.builtin.shell: |
        sudo -u mongodb mongos \
          --configdb {{ config_replset }} \
          --port {{ mongos_port }} \
          --bind_ip 0.0.0.0 \
          --fork \
          --logpath {{ log_path }} \
          --logappend
      args:
        creates: /tmp/mongos_started.flag
      register: mongos_start

    - name: Create flag file to prevent rerun of mongos
      ansible.builtin.file:
        path: /tmp/mongos_started.flag
        state: touch
      when: mongos_start is changed


    - name: Add rsShard1 and rsShard2 via mongos
      shell: |
        mongosh --host localhost --port {{ mongos_port }} <<EOF
        sh.addShard("{{ rsshard1 }}");
        sh.addShard("{{ rsshard2 }}");
        EOF
      register: add_shards_result

    - name: Show shard addition result
      debug:
        var: add_shards_result.stdout_lines
