---
- name: Run MongoDB Restore
  hosts: mongos
  become: yes
  vars:
    restore_script: /usr/local/bin/mongo_restore.sh
    restore_date: "{{ date | default('2025-06-04') }}"
  tasks:
    - name: Execute Restore.sh with date {{ restore_date }}
      shell: |
        bash {{ restore_script }} {{ restore_date }}
      register: restore_output

    - name: Show restore output
      debug:
        var: restore_output.stdout_lines
