---
- name: Run MongoDB sharding script
  hosts: mongos
  become: yes
  vars:
    script_path: /home/matilda-svc/scripts/sharding.js
    mongos_port: 27027
  tasks:
    - name: Execute sharding.js via mongosh
      shell: |
        mongosh --host localhost --port {{ mongos_port }} {{ script_path }}
      register: sharding_output

    - name: Show sharding script result
      debug:
        var: sharding_output.stdout_lines

